# Generated by Django 2.1.3 on 2018-12-12 15:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='u标题', max_length=400)),
                ('content', models.TextField(help_text='u正文')),
                ('createdate', models.DateTimeField(default=datetime.datetime(2018, 12, 12, 23, 22, 20, 898106))),
                ('author', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tips', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='tips',
            field=models.ForeignKey(on_delete=None, to='Portal.Tips'),
        ),
    ]
