# Generated by Django 2.1.3 on 2018-12-12 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_auto_20181212_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 23, 22, 52, 455074)),
        ),
    ]
