# Generated by Django 2.1.3 on 2018-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_auto_20181213_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tips',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='Portal.Tips'),
        ),
    ]
